import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import {
  predict,
  generateReport,
  getReport,
  listHistory,
  getHistoryItem,
  checkHealth,
  ApiError,
  PredictResponse,
  Report,
  TestRecordListItem,
  TestRecordResponse,
  HealthStatus,
} from './client';

describe('API Client', () => {
  const originalFetch = global.fetch;

  beforeEach(() => {
    vi.restoreAllMocks();
  });

  afterEach(() => {
    global.fetch = originalFetch;
  });

  it('predict() constructs valid multipart request and returns PredictResponse', async () => {
    const mockResponse: PredictResponse = {
      test_record_id: 'test-uuid-1234',
      prediction: 'parkinsons_risk_indicated',
      probability: 0.884,
      threshold_used: 0.55,
      attention: {
        timestamps_sec: [0.0, 1.0],
        attention: [0.3, 0.7],
      },
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => mockResponse,
    });

    const dummyBlob = new Blob(['dummy audio content'], { type: 'audio/wav' });
    const result = await predict(dummyBlob, 'PATIENT-001', 'recording');

    expect(global.fetch).toHaveBeenCalledTimes(1);
    const [url, options] = (global.fetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toContain('/api/v1/predict');
    expect(options.method).toBe('POST');
    expect(options.body).toBeInstanceOf(FormData);

    expect(result).toEqual(mockResponse);
    expect(result.prediction).toBe('parkinsons_risk_indicated');
    expect(result.probability).toBe(0.884);
  });

  it('generateReport() posts to correct endpoint and returns Report object', async () => {
    const mockReport: Report = {
      model_prediction: {
        prediction: 'low_risk_indicated',
        probability: 0.12,
        threshold_used: 0.55,
      },
      retrieved_evidence: [
        { text: 'Normal vocal variation.', source_name: 'NIH', source_url: 'https://nih.gov' },
      ],
      generated_explanation: {
        screening_summary: 'Acoustic parameters fall within standard baseline variance.',
        explanation: 'Steady fundamental frequency and normal harmonic ratio.',
      },
      clinical_disclaimer: 'NOTICE: This report is generated by an automated screening tool.',
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => mockReport,
    });

    const report = await generateReport('rec-789');

    expect(global.fetch).toHaveBeenCalledTimes(1);
    const [url, options] = (global.fetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toContain('/api/v1/report/rec-789');
    expect(options.method).toBe('POST');
    expect(report).toEqual(mockReport);
  });

  it('getReport() fetches cached report for existing record', async () => {
    const mockReport: Partial<Report> = {
      clinical_disclaimer: 'Immutable disclaimer.',
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => mockReport,
    });

    const report = await getReport('rec-cached');
    expect(global.fetch).toHaveBeenCalledTimes(1);
    const [url, options] = (global.fetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toContain('/api/v1/report/rec-cached');
    expect(options.method).toBe('GET');
    expect(report.clinical_disclaimer).toBe('Immutable disclaimer.');
  });

  it('listHistory() correctly serializes pagination query params', async () => {
    const mockList: TestRecordListItem[] = [
      {
        id: 'rec-1',
        created_at: '2026-09-23T10:00:00Z',
        test_id: 'P1',
        source: 'upload',
        prediction: 'low_risk_indicated',
        probability: 0.2,
        threshold_used: 0.55,
        audio_duration_sec: 4.0,
        model_version: 'v1',
        has_report: false,
      },
    ];

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => mockList,
    });

    const result = await listHistory(25, 50);

    const [url, options] = (global.fetch as ReturnType<typeof vi.fn>).mock.calls[0];
    expect(url).toContain('/api/v1/history?limit=25&offset=50');
    expect(options.method).toBe('GET');
    expect(result).toHaveLength(1);
    expect(result[0].id).toBe('rec-1');
  });

  it('getHistoryItem() retrieves full record with attention heatmap JSON', async () => {
    const mockItem: TestRecordResponse = {
      id: 'rec-detail-1',
      created_at: '2026-09-23T10:00:00Z',
      test_id: 'P1',
      source: 'recording',
      prediction: 'parkinsons_risk_indicated',
      probability: 0.95,
      threshold_used: 0.55,
      audio_duration_sec: 3.5,
      model_version: 'v1',
      has_report: true,
      attention_heatmap_json: JSON.stringify({ timestamps_sec: [0.0], attention: [0.9] }),
      report_json: JSON.stringify({ status: 'ready' }),
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => mockItem,
    });

    const item = await getHistoryItem('rec-detail-1');
    expect(item.id).toBe('rec-detail-1');
    expect(item.attention_heatmap_json).toContain('timestamps_sec');
  });

  it('checkHealth() returns health check payload', async () => {
    const mockHealth: HealthStatus = {
      status: 'ok',
      model_artifact_found: true,
      timestamp: '2026-09-23T12:00:00Z',
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => mockHealth,
    });

    const health = await checkHealth();
    expect(health.status).toBe('ok');
    expect(health.model_artifact_found).toBe(true);
  });

  it('throws ApiError with status and detail when response is not ok', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      status: 400,
      statusText: 'Bad Request',
      json: async () => ({ detail: 'Unsupported audio format .exe' }),
    });

    await expect(predict(new Blob([]), 'TEST', 'upload')).rejects.toThrow(ApiError);
    await expect(predict(new Blob([]), 'TEST', 'upload')).rejects.toThrow('API Error 400: Unsupported audio format .exe');
  });

  it('throws ApiError 503 with setup instructions when LLM is unavailable', async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      status: 503,
      statusText: 'Service Unavailable',
      json: async () => ({
        detail: 'LLM service is currently unavailable. Please configure LLM_API_KEY in .env. See docs/LLM_SETUP.md.',
      }),
    });

    await expect(generateReport('rec-503')).rejects.toThrow('LLM service is currently unavailable');
  });
});
