"""Clinical Decision Support Report Generation Service for Parkinson's Voice Platform.

Orchestrates RAG evidence retrieval and grounded LLM synthesis to produce structured,
safety-reviewed screening reports.

SAFETY-CRITICAL ARCHITECTURE:
1. Clean Structural Separation:
   - model_prediction: raw neural network numbers, untouched by the LLM.
   - retrieved_evidence: authoritative literature passages from RAG, untouched by the LLM.
   - generated_explanation: LLM-synthesized narrative, strictly bounded by prompts.
   - clinical_disclaimer: immutable, hardcoded constant that cannot be altered or omitted.
2. Defense-in-Depth Safety Guardrails:
   - System prompt strictly bans diagnostic claims and mandates screening language.
   - Post-generation safety scan inspects output against a blocklist of forbidden phrases.
   - Any detected diagnostic assertion is discarded and replaced with a verified safe fallback.
"""

from typing import Any, Dict, List, Optional
import json
import logging
import re

from backend.app.config import Settings, get_settings
from backend.app.schemas.report import (
    EvidenceChunk,
    GeneratedExplanation,
    ModelPredictionSummary,
    Report,
)
from backend.app.services.inference import PredictionResult
from backend.app.services.llm import LLMError, LLMService
from backend.app.services.rag import RAGService, RetrievedChunk

logger = logging.getLogger("parkinsons_platform.report")


# ------------------------------------------------------------------------------
# Fixed, Non-Modifiable Clinical Disclaimer
# ------------------------------------------------------------------------------

CLINICAL_DISCLAIMER: str = (
    "NOTICE: This report is generated by an automated acoustic research and screening tool. "
    "It is NOT a medical diagnosis, diagnostic confirmation, or clinical evaluation of Parkinson's disease. "
    "Acoustic vocal variations may stem from various physiological, environmental, or temporary factors. "
    "This tool cannot establish the presence or absence of any medical condition. "
    "If you or someone you know has concerns about voice changes, movement symptoms, or neurological health, "
    "please consult a qualified healthcare provider, neurologist, or movement disorder specialist for a comprehensive clinical assessment."
)


# ------------------------------------------------------------------------------
# System Prompt & Guardrails
# ------------------------------------------------------------------------------

REPORT_SYSTEM_PROMPT: str = """You are an expert clinical decision support assistant for a non-diagnostic acoustic voice screening platform.
Your task is to synthesize an educational, plain-language explanation of an acoustic voice screening result.

MANDATORY SAFETY & ACCURACY RULES:
1. ACCURACY: Only reference the exact numeric probability score and classification label provided in the user data. Never invent, alter, or round numbers differently.
2. GROUNDING: Only cite factual statements that are directly supported by the provided retrieved evidence passages. Attribute each key claim to its source_name.
3. NON-DIAGNOSTIC VOCABULARY: NEVER use diagnostic words such as "diagnose", "diagnosed", "diagnosis", "confirmed", "positive diagnosis", or state "you have Parkinson's". Use strictly screening and pattern-similarity language (e.g., "elevated acoustic risk indicated", "statistical feature similarity", "acoustic baseline").
4. CLINICAL REFERRAL: Always emphasize that acoustic findings are exploratory screening signals and recommend formal in-person neurological evaluation for persistent symptoms.
5. NO INDIVIDUAL BIOLOGICAL CLAIMS: Frame all explanations as general educational characteristics of hypokinetic dysarthria and acoustic speech research, not certified claims about this specific patient's underlying neuropathology.

OUTPUT FORMAT:
Respond with ONLY a valid, parseable JSON object matching this schema:
{
  "screening_summary": "2-4 sentences interpreting the numerical probability score and classification threshold in clear, accessible language.",
  "explanation": "2-4 sentences describing the characteristic vocal and speech patterns associated with this type of screening result, citing the source_name for evidence points."
}
"""


# ------------------------------------------------------------------------------
# Safety Blocklist & Fallbacks
# ------------------------------------------------------------------------------

FORBIDDEN_DIAGNOSTIC_PHRASES: List[str] = [
    "you have parkinson",
    "you have pd",
    "diagnosed with",
    "confirmed case",
    "confirmed diagnosis",
    "positive diagnosis",
    "we diagnose",
    "has been diagnosed",
    "patient has parkinson",
    "definitely has",
    "diagnostic proof",
    "confirms parkinson",
]

SAFE_FALLBACK_EXPLANATION: Dict[str, Dict[str, str]] = {
    "parkinsons_risk_indicated": {
        "screening_summary": (
            "The acoustic screening model detected vocal features that exhibit statistical similarity "
            "to acoustic patterns documented in Parkinson's speech research. This numerical result serves "
            "strictly as an exploratory screening indicator rather than a medical determination."
        ),
        "explanation": (
            "According to peer-reviewed speech biomarker research and the Parkinson's Foundation, "
            "changes such as reduced vocal volume (hypophonia), subtle pitch instability, and minor "
            "timing variations frequently characterize hypokinetic dysarthria. However, benign vocal "
            "fatigue or temporary respiratory conditions can also influence these metrics, making "
            "professional neurological evaluation essential for persistent concerns."
        ),
    },
    "low_risk_indicated": {
        "screening_summary": (
            "The acoustic screening model found that the analyzed vocal sample conforms closely to typical "
            "normative speech baselines, resulting in a low-risk screening classification."
        ),
        "explanation": (
            "Acoustic stability and pitch parameters in this recording align with typical speech patterns "
            "documented in neurological reference literature. Because acoustic screening evaluates only "
            "specific vocal dynamics, any emerging or persistent motor or speech symptoms should always "
            "be reviewed by a qualified healthcare professional."
        ),
    },
}


# ------------------------------------------------------------------------------
# Report Service Implementation
# ------------------------------------------------------------------------------

class ReportService:
    """Orchestrates RAG retrieval and safety-reviewed LLM report generation."""

    def __init__(
        self,
        rag_service: Optional[RAGService] = None,
        llm_service: Optional[LLMService] = None,
        settings: Optional[Settings] = None,
    ):
        """Initialize ReportService with RAG and LLM components.

        Args:
            rag_service: Optional RAGService instance.
            llm_service: Optional LLMService instance.
            settings: Optional application settings singleton.
        """
        self.settings = settings or get_settings()
        self.rag_service = rag_service
        self.llm_service = llm_service

    def _ensure_services(self) -> None:
        """Lazily initialize services if not provided explicitly."""
        if self.rag_service is None:
            self.rag_service = RAGService(settings=self.settings)
        if self.llm_service is None:
            self.llm_service = LLMService(settings=self.settings)

    def _build_retrieval_query(self, prediction: PredictionResult) -> str:
        """Construct domain-focused retrieval query from prediction outcome."""
        if prediction.prediction == "parkinsons_risk_indicated":
            return (
                "vocal and speech changes in Parkinson's disease hypophonia "
                "monotone pitch articulation screening indicators"
            )
        else:
            return (
                "vocal speech health normal acoustic baseline "
                "Parkinson's screening limitations clinical evaluation"
            )

    def _build_user_prompt(
        self,
        prediction: PredictionResult,
        evidence: List[EvidenceChunk],
    ) -> str:
        """Construct structured user prompt containing real data and evidence excerpts."""
        evidence_sections = []
        for idx, item in enumerate(evidence, 1):
            evidence_sections.append(
                f"[Evidence {idx}] (Source: {item.source_name})\n{item.text}"
            )
        evidence_text = "\n\n".join(evidence_sections)

        prob_pct = prediction.probability * 100.0
        return (
            f"ACOUSTIC SCREENING MEASUREMENTS:\n"
            f"- Model Screening Outcome: {prediction.prediction}\n"
            f"- Calibrated Probability: {prediction.probability:.4f} ({prob_pct:.1f}%)\n"
            f"- Classification Threshold: {prediction.threshold_used:.4f}\n"
            f"- Acoustic Risk Tier: {getattr(prediction, 'risk_tier', 'N/A')}\n"
            f"- Audio Duration Analyzed: {prediction.audio_duration_sec:.2f} seconds\n\n"
            f"RETRIEVED AUTHORITATIVE EVIDENCE:\n"
            f"{evidence_text}\n\n"
            f"TASK:\n"
            f"Synthesize the report into exactly two sections grounded strictly in the evidence above:\n"
            f"1. 'screening_summary': 2-4 sentences explaining this score and threshold in plain language.\n"
            f"2. 'explanation': 2-4 sentences explaining characteristic vocal features and context, citing source_name.\n\n"
            f"Respond ONLY with a valid JSON object matching the required schema."
        )

    def _parse_llm_json(self, raw_text: str) -> Optional[Dict[str, str]]:
        """Defensively parse JSON from model response, handling markdown fences."""
        cleaned = raw_text.strip()
        # Strip markdown code blocks if present (```json ... ``` or ``` ... ```)
        if cleaned.startswith("```"):
            lines = cleaned.split("\n")
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            cleaned = "\n".join(lines).strip()

        try:
            parsed = json.loads(cleaned)
            if isinstance(parsed, dict) and "screening_summary" in parsed and "explanation" in parsed:
                return {
                    "screening_summary": str(parsed["screening_summary"]).strip(),
                    "explanation": str(parsed["explanation"]).strip(),
                }
        except Exception:
            pass

        # Regex fallback for embedded JSON object
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            try:
                parsed = json.loads(match.group(0))
                if isinstance(parsed, dict) and "screening_summary" in parsed and "explanation" in parsed:
                    return {
                        "screening_summary": str(parsed["screening_summary"]).strip(),
                        "explanation": str(parsed["explanation"]).strip(),
                    }
            except Exception:
                pass

        return None

    def _safety_check_text(self, text: str) -> bool:
        """Scan text case-insensitively for forbidden diagnostic assertions.

        Returns:
            True if text is safe; False if a forbidden diagnostic phrase is detected.
        """
        text_lower = text.lower()
        for phrase in FORBIDDEN_DIAGNOSTIC_PHRASES:
            if phrase in text_lower:
                logger.warning(
                    "Safety check triggered: forbidden diagnostic phrase '%s' detected in LLM output.",
                    phrase,
                )
                return False
        return True

    def generate_report(
        self,
        prediction: PredictionResult,
        fallback_on_unavailable: bool = True,
    ) -> Report:
        """Generate structured clinical decision support report for an acoustic screening result.

        Args:
            prediction: PredictionResult from neural network acoustic model.
            fallback_on_unavailable: If True, uses verified safe fallback text when LLM is offline.
                If False, raises LLMError so the caller can return an explicit 503.

        Returns:
            Report object with model_prediction, retrieved_evidence, generated_explanation,
            and immutable clinical_disclaimer.
        """
        self._ensure_services()

        # 1. Retrieve domain-grounding evidence from persistent ChromaDB
        query = self._build_retrieval_query(prediction)
        retrieved = self.rag_service.retrieve(query=query, top_k=4)

        evidence_list = [
            EvidenceChunk(
                text=chunk.text,
                source_name=chunk.source_name,
                source_url=chunk.source_url,
            )
            for chunk in retrieved
        ]

        model_summary = ModelPredictionSummary(
            prediction=prediction.prediction,
            probability=prediction.probability,
            threshold_used=prediction.threshold_used,
        )

        pred_key = (
            "parkinsons_risk_indicated"
            if prediction.prediction == "parkinsons_risk_indicated"
            else "low_risk_indicated"
        )
        safe_fallback = SAFE_FALLBACK_EXPLANATION[pred_key]

        # 2. Check LLM availability
        is_available, status_msg = self.llm_service.check_availability()
        if not is_available:
            if not fallback_on_unavailable:
                raise LLMError(f"LLM service is unavailable: {status_msg}")
            logger.info("LLM is unavailable (%s); populating verified safe fallback explanation.", status_msg)
            return Report(
                model_prediction=model_summary,
                retrieved_evidence=evidence_list,
                generated_explanation=GeneratedExplanation(**safe_fallback),
                clinical_disclaimer=CLINICAL_DISCLAIMER,
            )

        # 3. Formulate prompts and execute LLM generation
        user_prompt = self._build_user_prompt(prediction, evidence_list)
        parsed_explanation = None

        try:
            raw_response = self.llm_service.generate(
                system_prompt=REPORT_SYSTEM_PROMPT,
                user_prompt=user_prompt,
                temperature=0.2,
                max_tokens=1024,
            )
            parsed_explanation = self._parse_llm_json(raw_response)

            # Defensive retry once if parsing failed
            if parsed_explanation is None:
                logger.warning("First LLM JSON parse attempt failed. Retrying with explicit formatting directive...")
                retry_user_prompt = (
                    f"{user_prompt}\n\n"
                    "CRITICAL: Your previous response was not valid JSON. You MUST return ONLY a JSON object "
                    'with keys "screening_summary" and "explanation", with no preamble or markdown ticks.'
                )
                retry_response = self.llm_service.generate(
                    system_prompt=REPORT_SYSTEM_PROMPT,
                    user_prompt=retry_user_prompt,
                    temperature=0.1,
                    max_tokens=1024,
                )
                parsed_explanation = self._parse_llm_json(retry_response)

        except Exception as exc:
            logger.error("Error during LLM report synthesis: %s", exc, exc_info=True)
            if not fallback_on_unavailable:
                raise
            parsed_explanation = None

        # 4. Fallback if parsing failed after retry
        if parsed_explanation is None:
            logger.warning("LLM response could not be parsed into JSON. Applying verified safe fallback explanation.")
            explanation_data = safe_fallback
        else:
            # 5. Post-generation safety scan on both text fields
            summary_safe = self._safety_check_text(parsed_explanation["screening_summary"])
            explanation_safe = self._safety_check_text(parsed_explanation["explanation"])

            if not (summary_safe and explanation_safe):
                logger.warning(
                    "Safety check rejected LLM output due to prohibited diagnostic phrase. "
                    "Substituting safe generic fallback explanation."
                )
                explanation_data = safe_fallback
            else:
                explanation_data = parsed_explanation

        return Report(
            model_prediction=model_summary,
            retrieved_evidence=evidence_list,
            generated_explanation=GeneratedExplanation(**explanation_data),
            clinical_disclaimer=CLINICAL_DISCLAIMER,
        )


def get_report_service(request: Any) -> ReportService:
    """FastAPI dependency provider yielding ReportService wired to app state services."""
    rag_service = getattr(request.app.state, "rag_service", None)
    llm_service = getattr(request.app.state, "llm_service", None)
    return ReportService(rag_service=rag_service, llm_service=llm_service)
